### ISSUE TITLE
deprecate packethost/csi-packet

### ISSUE THREAD

**Issue by rainleander** [equinix-labs/equinix-labs#74]
Switch to Experimental with Deprecated Qualifier:

"Elastic Block Storage is only available in Core Legacy Sites: AMS1, DFW2, EWR1, NRT1, SJC1. If you do not have access to these sites, you may reach out to our support team to request it."

[0] https://equinixmetal.slack.com/archives/C010GRH2DRC/p1610652812016100
[1] https://metal.equinix.com/developers/docs/resilience-recovery/elastic-block-storage/#legacy-only-sites

**Comment by rainleander** [comment]
Also, can we lock down issues and pull requests to force people to get support via Customer Success?

**Comment by displague** [comment]
I think this project should move to the deprecated tier (#77) when that tier has been made ready.

**Comment by displague** [comment]
References to CSI-Packet have been removed in #78
