### ISSUE TITLE
Decide which repos from packet-labs should be moved into equinix-labs

### ISSUE THREAD

**Issue by alice-sowerby** [equinix-labs/equinix-labs#81]
https://github.com/packet-labs is going to be deprecated as an actively-used place to host repos. There are a lot of repos on it that we need to assess as to whether they are worth pulling across into equinix-labs. 

This will be raised as an agenda item in the next Equinix Labs administrator meeting (date TBC). 

* [x] https://github.com/packet-labs/iot/issues/97
* [ ] https://github.com/packet-labs/ContainerLinuxOnBareMetal/issues/10
* [x] https://github.com/packet-labs/terraform-metal-tanzu/issues/24
* [x] https://github.com/packet-labs/kubernetes-cloud-init/issues/1
* [x] https://github.com/packet-labs/tech-demos/issues/8
* [x] https://github.com/packet-labs/packet-plans/issues/8 (deleted, pre-fork repo is at https://github.com/Miouge1/packet-plans)
* [x] https://github.com/packet-labs/k8s-videos/issues/7
* [x] https://github.com/packet-labs/packetnet-fw-agent/issues/20
* [x] https://github.com/packet-labs/helm-charts/issues/21
* [x] https://github.com/packet-labs/packet-router/issues/10
* [x] https://github.com/packet-labs/Packet-BGP-LoadBalancing/issues/5 (Persists as https://github.com/jeffbrl/packet-cloud-bgp/pull/16)
* [x] https://github.com/packet-labs/full-metal-kube/issues/10
* [ ] https://github.com/packet-labs/EdgeAccelerator/issues/3
* [ ] https://github.com/packet-labs/EdgeAcceleratedWebsite/issues/3
* [x] https://github.com/packet-labs/api-training/issues/4
* [ ] https://github.com/packet-labs/AlgoTradingOnEquinixMetal/issues/3 
* [x] https://github.com/packet-labs/kubernetes-bgp/issues/26
* [x] https://github.com/packet-labs/BGP-Anycast-Workshop/issues/14
* [ ] https://github.com/packet-labs/Kata-on-Packet/issues/7
* [x] https://github.com/packet-labs/SecuringBareMetal/issues/6

---

* [x] packet-express-openshift-infra (archived)
* [x] packet-flatcar-linux-upgrade (archived)
* [x] vsphere-packet-tf (archived, moved to github.com/equinix/terraform-metal-vsphere)
* [x] appconfig (archived)
* [x] PacketNodePoolDriver (archived)
* [x] terraform-packet-vmware (deprecated, see https://github.com/equinix/terraform-metal-vsphere)
* [x] Packet-Terraform-Boilerplate (deprecated, see https://github.com/equinix-labs/terraform-equinix-template)
* [x] terraform-packet-connect (archived, service no longer provided, replaced with Equinix Metal Connections)

**Comment by displague** [comment]
We may need to consult #80 and decide when work should be done on repos that are slated to be moved here. Should the repos be _fixed up_ (per #80) before they are moved here, or is it fine to do this afterward?

**Comment by displague** [comment]
We've had no response on any of the issues linked above aside from terraform-metal-tanzu which has been moved to equinix-labs.

**Comment by displague** [comment]
I've run through the open issues again and there have been no additional comments. We will proceed with deleting (private+archiving) these repositories following the next Equinix Labs group meeting.
