### ISSUE TITLE
Add new Equinix Labs profile pic

### ISSUE THREAD

**Issue by alice-sowerby** [equinix-labs/equinix-labs#92]
Roni has designed this for us - pretty cool! 

I don't think I am able to update the logo on the GH Org, maybe @displague can?
![Equinix-Labs_Profile](https://user-images.githubusercontent.com/17722440/144336284-9dbf95b3-4aff-438d-98fd-887f3ac1276a.png)

**Comment by displague** [comment]
https://github.com/orgs/equinix-labs/people?query=role%3Aowner

@matoszz, can you help us set the image above as the profile picture for the equinix-labs org?
https://github.com/organizations/equinix-labs/settings/profile

**Comment by displague** [comment]
done
